### ISSUE TITLE
Support Tool Use

### ISSUE THREAD

**Issue by calclavia** [Mixpeal/anthropic-sdk#2]
It'll be great if we can update this package to support the new tool use API!

https://docs.anthropic.com/claude/docs/tool-use

If this is not WIP, I'm happy to make a PR.

**Comment by Mixpeal** [comment]
Hey, @calclavia thanks for notifying me, I am almost done with this, I am thinking of returning the whole response, let the developers parse it themselves (with serde).

What do you think?

**Comment by Mixpeal** [comment]
I am thinking of adding `verbose` mode too, in case the developer wants the entire response

**Comment by calclavia** [comment]
@Mixpeal returning the whole response works. Or you can take a serde deserialize generic and use serde to deserialize to the given struct type on your end.

**Comment by Mixpeal** [comment]
The issue is the response from Anthropic is not consistent, it's better to let developers parse it themselves, so it still works if it's no more in beta.

btw it's in the 0.0.8 I just publish now, you should check it out and let me know.
